<?php /* Smarty version 2.6.30, created on 2017-02-11 04:58:34
         compiled from index.html */

$this->_cache_serials['../templates_c/\%%77^774^774BE9C9%%index.html.inc'] = '94fcd4022430617d201befa8fd28b04c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'nocache', 'index.html', 16, false),)), $this); ?>
<?php
function _smarty_tplfunc_94fcd4022430617d201befa8fd28b04c_0(&$_smarty)
{
$_smarty->_tag_stack[] = array('nocache', array()); $_block_repeat=true;func($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], null, $_smarty, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $_COOKIE['student']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo func($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], $_block_content, $_smarty, $_block_repeat); }  array_pop($_smarty->_tag_stack); 
}



?>
